controllers/MemoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Memo;
use app\models\MemoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * MemoController implements the CRUD actions for Memo model.
 */
class MemoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Admin');
                        }
                    ],

                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Sekretaris');
                        }
                    ],

                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Manajer');
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Memo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MemoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Memo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Memo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Memo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_memo]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Memo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_memo]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Memo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Memo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Memo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Memo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(['login']);
        }elseif (Yii::$app->user->identity->role=='Pegawai') {
            $this->redirect(['pegawai']);
        }else
            return $this->render('index');
    }

    public function actionPegawai(){
        $this->layout = 'guestLayout';

        return $this->render('pegawai-index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/SuratController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Surat;
use app\models\SuratSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * SuratController implements the CRUD actions for Surat model.
 */
class SuratController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Admin');
                        }
                    ],

                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Sekretaris');
                        }
                    ],

                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view'
                        ],
                        'allow' => true,
                        'matchCallback' => function(){
                            return(Yii::$app->user->identity->role=='Manajer');
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Surat models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SuratSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Surat model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Surat model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Surat();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_surat]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Surat model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_surat]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Surat model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Surat model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Surat the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Surat::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Dashboard Petinggi';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>STRONG HRD - DIREKSI</h1>

        <p class="lead">Buat Pegawai Baru Sekarang !</p>

        <p><?= Html::a('Buat Pegawai Baru', ['/pegawai/create'],['class'=>'btn btn-lg btn-success'])?></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Assign Posisi</h2>

                <p>Cek dan assign posisi dan peran pegawai</p>

                <p><?= Html::a('Lihat Absensi &raquo;', ['/posisi/create'],['class'=>'btn btn-info'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Absensi</h2>

                <p>Cek rekap absensi pegawai, dan atur absensi pegawai</p>

                <p><?= Html::a('Lihat Absensi &raquo;', ['/rekap-absensi'],['class'=>'btn btn-primary'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Assign Jadwal Lembur</h2>

                <p>Assign jadwal lembur pegawai, dan atur pengaturan lemburnya</p>

                <p><?= Html::a('Jadwal Lembur &raquo;', ['/lembur/create'],['class'=>'btn btn-warning'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Memo</h2>

                <p>Buat memo untuk disampaikan ke pegawai yang lain secara instan</p>

                <p><?= Html::a('Buat Memo &raquo;', ['/memo/create'],['class'=>'btn btn-warning'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Prestasi Pegawai</h2>

                <p>Tambah detail prestasi para pegawai</p>

                <p><?= Html::a('Prestasi Pegawai &raquo;', ['/prestasi/create'],['class'=>'btn btn-primary'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Surat</h2>

                <p>Atur dan ubah status surat (Khusus Manajer)</p>

                <p><?= Html::a('ACC Surat &raquo;', ['/surat/index'],['class'=>'btn btn-info'])?></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with username and password you apropriate.<br>
        If there have a problem please ask administration.
    </div>
</div>

views/site/pegawai-index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
$idpeg = Yii::$app->user->identity->id_pegawai;
$this->title = 'Dashboard Pegawai';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>STRONG HRD - PEGAWAI</h1>

        <p class="lead">Lihat Data Diri Sekarang!</p>

        <p><?= Html::a('Lihat Data Diri', ['/pegawai/view', 'id' => $idpeg ],['class'=>'btn btn-lg btn-success'])?></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Absensi</h2>

                <p>Lakukan Absensi</p>

                <p><?= Html::a('Absen &raquo;', ['/submit-absensi'],['class'=>'btn btn-primary'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Posisi</h2>

                <p>Lihat Keterangan Posisi</p>

                <p><?= Html::a('Lihat Posisi', ['/lihat-posisi', 'id' => $idpeg ],['class'=>'btn btn-success'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Prestasi</h2>

                <p>Lihat Prestasi</p>

                <p><?= Html::a('Lihat Daftar Prestasi', ['/daftar-prestasi', 'id' => $idpeg ],['class'=>'btn btn-info'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Lihat Jadwal Lembur</h2>

                <p>Lihat Jadwal Lembur Anda</p>

                <p><?= Html::a('Jadwal Lembur &raquo;', ['/jadwal-lembur'],['class'=>'btn btn-warning'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Memo</h2>

                <p>Lihat Memo yang Sedang Aktif</p>

                <p><?= Html::a('Lihat Memo &raquo;', ['/lihat-memo'],['class'=>'btn btn-warning'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Request Surat</h2>

                <p>Buat Permohonan Surat</p>

                <p><?= Html::a('Request Surat Ijin &raquo;', ['/submit-surat/surat-ijin'],['class'=>'btn btn-info'])?></p>
                <p><?= Html::a('Request Surat Cuti &raquo;', ['/submit-surat/surat-cuti'],['class'=>'btn btn-warning'])?></p>
                <p><?= Html::a('Request Surat Jalan &raquo;', ['/submit-surat/surat-jalan'],['class'=>'btn btn-primary'])?></p>
                <p><?= Html::a('Request Surat Keterangan Gaji &raquo;', ['/submit-surat/surat-gaji'],['class'=>'btn btn-success'])?></p>
                <p><?= Html::a('Request Surat Pengunduran diri &raquo;', ['/submit-surat/surat-pengunduran'],['class'=>'btn btn-warning'])?></p>
            </div>

            <div class="col-lg-4">
                <h2>Lihat Status Surat</h2>

                <p>Lihat Status Surat yang Telah Diajukan</p>

                <p><?= Html::a('Lihat Status Surat &raquo;', ['/lihat-surat'],['class'=>'btn btn-info'])?></p>
            </div>
        </div>

    </div>
</div>